// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZVG-uAAosSrjHcYJRq3zbwTXWjHzz3lQ',
    appId: '1:843584449870:android:8ff2d8eb5ddd03d39d021f',
    messagingSenderId: '843584449870',
    projectId: 'traveltech-f0674',
    storageBucket: 'traveltech-f0674.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBButELbef_Z9XOEhKi4XxZElHa1ruIiX8',
    appId: '1:843584449870:ios:cc73530e38256e5f9d021f',
    messagingSenderId: '843584449870',
    projectId: 'traveltech-f0674',
    storageBucket: 'traveltech-f0674.firebasestorage.app',
    androidClientId: '843584449870-i8np84sgo65alat9u8vqnmnvg67hucm8.apps.googleusercontent.com',
    iosClientId: '843584449870-3fubklkfa29kflp7dakbnbonhbhucdrv.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );
}
